services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    # image: mongo:7
    container_name: gift-app-integration-mongo
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/etc/mongo-keyfile" ]
    # command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}) }" | mongosh --port 27017 -u admin -p password --authenticationDatabase admin
      interval: 5s
      timeout: 30s
      start_period: 15s
      start_interval: 1s
      retries: 30
    env_file: ../.env.test
    restart: no
    ports:
      - "27017:27017"
    # volumes:
    #   - ${PWD}/rs_keyfile:/data/replica.key.d
    # entrypoint:
    #   - bash
    #   - -c
    #   - |
    #     cp /data/replica.key.d /data/replica.key
    #     chmod 400 /data/replica.key
    #     chown 999:999 /data/replica.key
    #     exec docker-entrypoint.sh $$@     
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
